- .travis.yml
- Dockerfile
- cloudbuild.yaml
- docker-compose.yaml
- requirements.txt
- scripts/testing/run_tests.sh
- setup.py
Pulling in testing and setup related changes that were originally part of work done on #5.
> Testing and Setup Updates

- docs/requirements.txt
- docs/source/conf.py
See: https://github.com/sphinx-doc/sphinx/issues/3800
>  Removing recommonmark and rely only on m2r

- CHANGELOG.md
- panoptes_utils/version.py
- setup.cfg
Merge back changes from the release.
> Release 004

- panoptes_utils/__init__.py
- setup.py
More testing of auto pypi builds.
> Testing better version import

- panoptes/utils/error.py
- panoptes/utils/rs232.py
- panoptes/utils/serializers.py
- panoptes/utils/tests/serial_handlers/protocol_arduinosimulator.py
Use our serializers in the rs232 library.  Preparation for moving to arduinojson
> Serialization Updates for rs232

- bin/panoptes-messaging-hub
- docker/Dockerfile.utils.amd64
- docker/Dockerfile.utils.rpi
* Fix messaging port. (didn't I do this already?)
* Download astrometry into location that allows for easy volume mapping
> Misc small fixes

- conftest.py
- docker/Dockerfile.utils
- panoptes/utils/config/server.py
- panoptes/utils/messaging.py
- panoptes/utils/tests/test_messaging.py
- scripts/testing/run-tests.sh
- scripts/testing/test-software.sh
Make the messaging tests work in a similar manner to how POCS requires. Some log level changes.
> Messaging and Log Updates

- panoptes/utils/images/cr2.py
- panoptes/utils/images/fits.py
* Don't show solve warning unless we actually have an error
* Fix call to updating observation headers from CR2
> Small updates

- bin/panoptes-messaging-hub
- docker/Dockerfile.utils
- panoptes/tests/panoptes_utils_testing.yaml
- panoptes/utils/google/storage.py
- panoptes/utils/serializers.py
* Check for messaging ports in a better way
* Copy over zshrc file to docker
* Remove unused function
* Adding deserialization convenience for the following units:
* deg -> degree
* m -> meter
* s -> second
See examples.
Note: not sure this is a great idea.
> Working changes

- README.md
- scripts/create-hotspot.sh
Script to set up a local hotspot. Useful for situations when main computer is plugged into ethernet but has an open wifi card available. 
Replaces part of #51
> Add hotspot script

- panoptes/utils/data.py
Use self-hosted mirror for IERS files.
Matches https://github.com/panoptes/POCS/pull/876
> Use self-hosted IERS mirror

- panoptes/utils/config/client.py
- panoptes/utils/images/fits.py
Minor changes to output errors when timeout happens on solve.
> Output errors on timeout solve

- docker/Dockerfile
- docker/Dockerfile.utils
- docker/entrypoint.sh
- panoptes/utils/config/client.py
- scripts/build_containers.sh
* Adding conda paths to bash in addition to zsh.
* Make sure scripts are run interactively.
* Build container is not async.
> Docker container updates

- panoptes/utils/bayer.py
Some updates that have been in progress. Mostly faster and more efficient slicing of the RGB channels.
> Some updates for color channels

- panoptes/utils/error.py
- panoptes/utils/utils.py
Helper functions to get the `sequence_id` or `image_id` from a path or uri.
> Image id helper

- panoptes/utils/images/__init__.py
- panoptes/utils/images/plot.py
- requirements.txt
- setup.py
Issues identified by flake8 and removal of google modules.
> Minor cleanup

- docker/Dockerfile.utils
- setup.py
> Deal with some dependencies better

- .coveragerc
- .github/workflows/pythonpackage.yml
- .github/workflows/pythonpublish.yaml
Github actions with testing and building of pypi package.
Closes #107
> Github Actions and Testing

- .github/workflows/pythonpublish.yaml
- .github/workflows/pythontest.yaml
- docker/Dockerfile.utils
- docker/docker-compose.yaml
- panoptes/tests/panoptes_utils_testing.yaml
- scripts/testing/test-software.sh
* Test on all push and pull requests
* Build `panoptes-utils` image and use that for testing.
* On `master`, also build `panoptes-base` (although it doesn't yet use that).
* Publish to test pypi on `develop` and pypy on `master`.
* Updates to project name.
> Separate GitHub Action files

- conda-requirements-amd64.yaml
- panoptes/utils/tests/serial_handlers/protocol_arduinosimulator.py
Small fixes discovered from POCS update.
> Pocs fixes

- .github/workflows/pythontest.yaml
- .travis.yml
- CHANGELOG.md
- conftest.py
- panoptes/utils/logger.py
- panoptes/utils/tests/images/test_image_utils.py
- scripts/testing/run-tests.sh
* Send codecov report from Action.
* Add better names for steps.
* Artifact of log file.
* Don't update repo on test run.
> Github Actions Testing Improvements

- CHANGELOG.md
- README.md
- conftest.py
- docker/Dockerfile
- docker/Dockerfile.utils
- panoptes/utils/images/fits.py
- panoptes/utils/tests/images/test_fits_utils.py
* Data files are copied to temp directory before used in tests so original is always preserved.
Affects #140 
Closes #141
> Use copy of testing data files in tests

- CHANGELOG.md
- panoptes/utils/images/bayer.py
- panoptes/utils/serializers.py
- panoptes/utils/tests/test_serializers.py
* Fix `args` and `kwargs` in `get_rgb_background`
* Added basic serialization of exceptions.
> Plate solver fixes

- CHANGELOG.md
- panoptes/utils/utils.py
* Camera id can include a zero.
* `image_id_from_path` and `sequence_id_from_path` return `None` when no match.
> Match sequence ids and image ids better.

- CHANGELOG.md
- panoptes/utils/sources.py
* Accept either a `WCS` or the output from `calc_footprint()` for looking up sources.
* Fix index.
> Source lookup fixes for pipeline

- CHANGELOG.md
- panoptes/utils/sources.py
- panoptes/utils/utils.py
- requirements.txt
- setup.py
> Adding bigquery client to the `sources` module.

- CHANGELOG.md
- panoptes/utils/utils.py
* More readable regexp.
* Unquote any paths before match.
> Improved Path Matcher Util

- CHANGELOG.md
- panoptes/utils/sources.py
:beetle:  Do WCS match for all unmatched sources, not just matched sources.
:heavy_plus_sign: `status` column with values {`matched`, `unmatched`}
> Unmatched sources fix

- docker/latest.Dockerfile
- panoptes/utils/data/__init__.py
The dev headers were missing from the docker image.
> Adding libzmq3

- CHANGELOG.md
- panoptes/utils/data/__init__.py
- requirements.txt
- setup.py
Use static files for searching and returning metadata.
Note that this removes the individual image level for now.
Removes firestore dependencies
Closes #179
> Cache metadata search

- CHANGELOG.md
- panoptes/utils/data/metadata.py
* Return sorted by time.
* Filter the fields at the parquet level.
* Optional progress bar.
> get_observation fixes

- conftest.py
- setup.cfg
- src/panoptes/utils/data/metadata.py
- src/panoptes/utils/images/fits.py
- tests/test_theskyx_utils.py
* Disabling TheSkyX tests for now as Mocket is interferring with the config server.  Need to replace Mocket anyway. Future PR.
* Fixing doctest options including whitespace issues.
Closes #199
> Re-enable doctests

- .github/workflows/pythontest.yaml
- .travis.yml
- CHANGELOG.rst
- README.rst
- conftest.py
- docker/testing.Dockerfile
- docs/conf.py
- docs/index.rst
- docs/requirements.txt
- src/panoptes/utils/database/base.py
- src/panoptes/utils/images/bayer.py
- src/panoptes/utils/time.py
- tests/images/test_image_utils.py
- tests/test_rs232.py
* Doc style
* Adding CR2 files, closes #125
> Misc updates

- .github/codecov.yaml
- .github/workflows/pythontest.yaml
- .readthedocs.yaml
- scripts/testing/run-tests.sh
- scripts/testing/test-software.sh
- setup.cfg
Trying to clean up more tests from coverage decrease in #218 
Also fixes doc building for readthedocs.
> Config server tests

- CHANGELOG.rst
- docker/setup-local-environment.sh
- src/panoptes/utils/utils.py
* Change `dir` to `directory` in disk space check.
* Pass the git context when building docker images locally.
> Remove reserved keyword

- docker/cloudbuild.yaml
> Cloudbuilding

- .gcloudignore
- docker/Dockerfile
- docker/cloudbuild.yaml
* Trying to unshallow the git
Still resolving the issue with GCR and GHA: https://cloud.google.com/cloud-build/docs/automating-builds/create-github-app-triggers#data_sharing
> Fix cloudbuild and gha (yet again)

- CHANGELOG.rst
- docker/cloudbuild.yaml
* Pass the newly built base image to the utils image for testing.
* Make cloudbuild slightly more generic.
(there's always one little thing...)
> Properly pass new base image to utils build image.

- docker/cloudbuild.yaml
* Fix pushed name on cloudbuild.
> Docker fix

- CHANGELOG.rst
- docker/base/Dockerfile
- scripts/download-data.py
- scripts/setup-local-environment.sh
* Remove miniforge install from docker image.
* Fix build-args in docker-compose.
* Small improvement to download-data.
> Docker cleanup based off live run.

- CHANGELOG.rst
- docker/developer/Dockerfile
- docker/developer/docker-compose-developer.yaml
- scripts/setup-local-environment.sh
- src/panoptes/utils/config/cli.py
- src/panoptes/utils/config/client.py
Docker Tools:
* Adds a "developer" dockerfile and compose file to install things for developers. 
* Docker `CMD` will run `ipython`.
* docker-compose file will start a `jupyter-lab` instance.
Config Server:
* Option to start a heartbeat or not.
> Add processing tools

- CHANGELOG.rst
- docker/base/Dockerfile
- resources/docker/install-ohmyzsh.sh
* Local oh-my-zsh installation because of some certificate issues.
* Adding `source-extractor` with no config.
> More docker build fixes for pipeline automation.

- src/panoptes/utils/images/fits.py
* Removing the magic timeout number.
> FITS utils fixes and updates

- CHANGELOG.rst
- docker/Dockerfile
* Update `conda` in Dockerfile before installing environment.
* Install module in user-editable mode.
> Update conda in Docker image

- CHANGELOG.rst
- docker/Dockerfile
- docker/cloudbuild.yaml
Pushes the intermediate layers so they can be used for caching. Mostly will help with POCS.
Adds `neovim`, and `nano`.
> Cache docker builds

- CHANGELOG.rst
- docker/Dockerfile
- src/panoptes/utils/config/helpers.py
* Properly resolve the `base_dir` if given as current dir (i.e. `./`).
> Config base dir fixes

- CHANGELOG.rst
- docker/Dockerfile
- docker/docker-compose.yaml
- tests/Dockerfile
* Add `PYTHONUNBUFFERED` to docker files.
* Remove `version` and `deploy` keys from docker compose files.
> Docker updates

- docker/Dockerfile
- tests/test_time.py
* Use mambaforge directly instead of miniforge3.
> Use mambaforge as base image.

- setup.cfg
- setup.py
- src/panoptes/__init__.py
* Explicitly declare the `src` dir and remove the init file to properly support pep 420 style namespace.
> Fix namespace

- CHANGELOG.rst
- docs/conf.py
- docs/contributing.rst
- setup.cfg
- src/panoptes/utils/images/plot.py
Adding sphinx matplotlib directives and some coverage for the `plot` module.
Closes #112.
> Adding plot directives.

- src/panoptes/utils/images/misc.py
- src/panoptes/utils/images/plot.py
- tests/images/test_image_utils.py
* Better docs for `crop_data` and `mask_saturated`.
> Docs update for misc image functions

- src/panoptes/utils/serializers.py
Suppress all exceptions related to date parsing of yaml, so only allow it if it actually parses something.
> Fix parsing
