panoptes_utils/serializers.py

* Use `json` module everywhere since no `orjson` on arm platforms (rpi). Could be smarter and split it up but this is easy.
* Skip some of the doctests so the values shown in the docs make more sense.
**Edit: No longer serializes datetimes properly**
Closes #14

Revert to `json` over `orjson`.

---

panoptes_utils/logger.py

We are assuming that PANLOG will not change. Not that this change is necessary to support reading the logs in a docker container as symlinks give all kinds of trouble. Absolute paths make it a lot easier.
Small cleanup to symlink removal.

Use an absolute path for linking the log files. 

---

README.md
bin/panoptes-config-server
conftest.py
panoptes/utils/config/README.md
panoptes/utils/config/server.py

Adds a function that will start the config server in a separate process. Can be used to start and kill an instance of the server easily.
Cleanup to scripts and testing.

Config server convenience

---

panoptes/utils/database/file.py
panoptes/utils/serializers.py

When `to_json` is given a `filename`, default to appending to the file so it is not unknowingly clobbered.  Change `FileDB` to match.

JSON file write defaults to append.

---

panoptes/utils/serializers.py

Errors if string can't be split are ignored. This happens for an empty string, i.e. `"".rsplit()[-1]`

Handle some error strings.

---

README.md
panoptes/utils/config/README.md

* Add extra example of retreiving entire config key.
* Fix some code items that were adjusted by a previous auto-format.
Closes #62. This is the same thing only properly based off upstream.

Adjust docs for some config-server python examples.

---

panoptes/utils/images/__init__.py
panoptes/utils/tests/test_image_utils.py

Updates the `crop_data` utility function to use `astropy.nddata.Cutout2D` under the hood, which allows for passing a WCS and getting a crop of the WCS as well.  The function now has a parameter, `data_only` that is `True` by default and mimics the behvaiour of just returning the data. If `data_only=False` then the `Cutout2D` object is returned.

Better crop utility

---

panoptes/utils/logger.py

Fixing import warning to prevent breaking behavior before 3.8

Fix collections import

---

panoptes/utils/tests/test_utils.py
panoptes/utils/utils.py

Current behavior returns a list of dict_values or dict_keys. Current behaviour just wraps the dict_values in a list, e.g. `[dict_values('x')]` instead of `[x]`
May help with the autofocus breaking we are seeing in https://github.com/AstroHuntsman/huntsman-pocs

Handle dict keys and values appropriately.

---

conftest.py
panoptes/utils/config/client.py
panoptes/utils/config/server.py
panoptes/utils/database/file.py
panoptes/utils/library.py
panoptes/utils/serializers.py
panoptes/utils/tests/test_config_server.py
panoptes/utils/tests/test_serializers.py
panoptes/utils/tests/test_utils.py

Changes for panoptes-utils derived from upstream POCS changes. Part of https://github.com/panoptes/POCS/pull/951
* Config server will return `None` rather than raise exception and fail.
* :beetle:  Handle empty dict in serializer ~~(note that this duplicates #85 although that adds tests)~~
* Updates to `load_c_library` (https://github.com/panoptes/POCS/commit/d5cf73755a08a2e2d6ed2e5d5565ac7507c9ed2c)
* Tests and cleanup.

POCS Merge Updates

---

panoptes/utils/tests/test_utils.py
panoptes/utils/time.py
requirements.txt

Closes #83 and https://github.com/panoptes/POCS/pull/949

Forcing datetime to utc

---

CHANGELOG.md
panoptes/utils/error.py
panoptes/utils/tests/test_errors.py

* Always log the error message.
* If exiting, add handler to display message in terminal.
* Properly pass `kwargs` from child exceptions (so you can actually exit)

Exception fixes:

---

CHANGELOG.md
panoptes/__init__.py
panoptes/utils/__init__.py
setup.py

In order to properly use the `panoptes` namespace in other repos we need to drop the top level init.
See [docs](https://packaging.python.org/guides/packaging-namespace-packages/#native-namespace-packages)

Fix namespace

---

CHANGELOG.md
requirements.txt
setup.py

The have been moved to the `dev` extras and can be installed with `pip install panoptes-utils[dev]` (or just `.[dev]` if you are inside the directory).

Remove some modules that will be deprecated soon.

---

CHANGELOG.md
setup.py

* Explicit namespace search.
* Also removing zips. See note at bottom of: https://github.com/pypa/sample-namespace-packages

Fix for 'panoptes' namespace across distributions.

---

CHANGELOG.md
panoptes/utils/images/bayer.py

Following on #162, instead of just returned the separate masked arrays, return the actual `Background2D` object. This gives access to the RMS mesh grid and other properties of each computed background.

Allow for RGB background object to be returned

---

.coveragerc
panoptes/utils/data.py
requirements.txt
setup.cfg
setup.py

This PR creates three functions:
* `get_data` is a wrapper around the more specific functions. For now that is `get_image` and `get_observation`.
* `get_image` will download a fits image.
* `get_observation` downloads a dataframe with image metadata for all images in the observation.
This PR has a working (but limited) `get_image` and `get_observations`.
~~`get_image` currently it does a lookup on the firestore db in order to get the full path (because the `sequence_id` is not part of the `image_id`) and then uses the google client to download files.~~
~~Alternatively we could create a cloud function that hides the details of firestore (so the user doesn't need login access). Likewise, we could download via the public url and `requests` rather than use the google storage libraries.~~ …

Initial commits for some of the data access components.

---

CHANGELOG.md
panoptes/utils/images/fits.py

* Fix a usage problem where you either had to pass all possible desired options or just accept most of the defaults. 
* Changes default options in `get_solve_field` to use `scale-low` and ` scale-high` instead of `radius` (which requires an `ra` and `dec`).
* Fixes bug where `args` and `kwargs` weren't being properly passed in `getdata`.
This PR fixes so that you can pass `args` and `kwargs` to `solve-field` and they will be added to the list of default options.  
These currently will **not** override the defaults, which would be desirable, but merely allow you to specify additional options in addition to the default.

More flexible solve options

---

CHANGELOG.md
panoptes/utils/data/__init__.py
panoptes/utils/images/fits.py
panoptes/utils/tests/images/test_fits_utils.py

* `get_solve_field` will only accept `kwargs` for passing to `solve_field`. Single keyword options should have a bool, e.g. `{'--overwrite': True}`

Solve field fixes.

---

CHANGELOG.md
panoptes/utils/data/metadata.py
panoptes/utils/images/bayer.py
panoptes/utils/stars.py
panoptes/utils/tests/images/test_bayer.py
resources/sextractor/panoptes.sex

* Add `bayer.get_stamp_slice` for getting a stamp slice while respecting the superpixel. This was removed awhile ago and has been re-added and improved.
* Only support getting stars directly from the WCS, not the footprint.
* `get_stars_from_footprint` -> `get_stars_from_wcs`
* Better logging
* Consistent column names for dtypes
* Vmag bin comes from sql.
* Allow for different RA/Dec column names.
* Better catalog match function.
* sextractor param changes

Image processing tools and solver updates

---

CHANGELOG.rst
src/panoptes/utils/time.py
tests/test_time.py

Adding the `wait_for_events` and making more generic. Example usage in the docstring.
Replaces the `pocs.wait_for_events` that is used to control some of the state logic.
Slipping in some changelog reformatting. Just changing headings.
Closes #92 (sure, why not?)

Generic wait_for_events utility.

---

CHANGELOG.rst
src/panoptes/utils/time.py
tests/test_time.py

* More generic `callback` parameter. Repalces the `msg_interval`, which wasn't used properly outside of POCS.

More generic wait_for_events

---

docker/setup-local-environment.sh
src/panoptes/utils/stars.py

`get_catalog_match` added a `catalog_stars` param that can be used for the matching. This is done so the catalog query doesn't have to be performed multiple times for the same observation.
Closes #215

Catalog match accepts catalog stars as param.

---

CHANGELOG.rst
conftest.py
setup.cfg
src/panoptes/utils/config/__init__.py
src/panoptes/utils/config/client.py
src/panoptes/utils/config/server.py
src/panoptes/utils/serializers.py
tests/test_config_server.py
tests/test_serializers.py

* Cleaning up the config_server.
* Better logging.
* Cleaning up doctests.
* Removing all dynamic server items from this repo as they are not needed.
* Wait for config_server to start.
* Fixing starting within fixture.
* Serializers update
* Make the parsing and serializing functions public.
* Use pendulum for parsing times instead of astropy Time.
Closes #110 
Closes #111

Config server tests

---

.github/codecov.yaml
.github/workflows/pythontest.yaml
.travis.yml
CHANGELOG.rst
conftest.py
docs/index.rst
scripts/testing/run-tests.sh
scripts/testing/test-software.sh
setup.cfg
src/panoptes/utils/config/__init__.py
src/panoptes/utils/config/client.py
src/panoptes/utils/config/server.py
src/panoptes/utils/serializers.py
tests/images/test_fits_utils.py
tests/test_config.py
tests/test_theskyx_utils.py
tests/test_time.py

Config changes
* Config items no longer assume any defaults for either directories or files. A config file name is always required and it should always be an absolute path.
* Adding test file for config items.
Serializers:
* Better naming of public functions.
Misc:
* Running pytest locally will generate coverage report in terminal.
* Lots of documentation.
* Removing the environment section from the readme.
#217 
#111 
#110

Config and serializer changes.

---

conftest.py
src/panoptes/utils/database/base.py
src/panoptes/utils/database/file.py
src/panoptes/utils/database/memory.py
tests/test_database.py

* Allow the file storage dir to be customized.
* Still assumes the directory is relative to `$PANDIR`.
Closes #87 
Required by https://github.com/panoptes/POCS/pull/957

Custom DB folder.

---

src/panoptes/utils/images/__init__.py
src/panoptes/utils/images/focus.py
tests/images/test_focus_utils.py

`panoptes.utils.images.mask_saturated()` function currently works with either a directly specified `saturation_level` (an optional argument), or by attempting to infer the maximum pixel value and multiplying that by a `threshold` (another optional argument, which defaults to 0.9). There are several problems with the way it infers the maximum pixel value:
1. The use of data type to infer maximum pixel value will give the wrong result if the actual bit depth of the data is lower than the data type would imply (e.g. images from 12 or 14 bits/pixel cameras in `numpy.uint16` arrays).
1. If the data type is not an integer type it is silently assumed that the maximum pixel value is `2**16 - 1`, but in general this will not be true.
This PR addresses these problem by:
1. Adding an optional …

Add bit_depth argument to mask_saturated, no longer convert to float64 by default

---

.github/workflows/pythontest.yaml
CHANGELOG.rst
resources/environment.yaml
scripts/download-data.py
setup.cfg
src/panoptes/utils/config/cli.py
src/panoptes/utils/config/client.py
src/panoptes/utils/config/helpers.py
src/panoptes/utils/config/server.py
src/panoptes/utils/images/__init__.py

Some compatibility issues down the chain, so we want to keep this at 3.7 for now. Mostly this means removing the `{=}` construct.
Also locking astropy version until updated astroplan available (see https://github.com/astropy/astroplan/issues/485).

Move back to python 3.7

---

CHANGELOG.rst
docker/base/Dockerfile
docker/cloudbuild.yaml
scripts/testing/test-software.sh

* Fix zsh install path. The `oh-my-zsh` repo has moved into a new top-level project so the url has changed. Make it an `ARG` while we're at it.
* Fix test output return, closes #247 
* Default to `develop` tag for cloudbuild images.

Docker build updates - zsh fixes

---

src/panoptes/utils/time.py
tests/test_time.py

* Defaults to a `TRACE` level to not generate noise, but can be set via a parameter.
Future improvements would be to give a status update every `x` seconds if the sleep time is greater than some `y`.
Closes #258

Improved log message for CountdownTimer sleep

---

CHANGELOG.rst
docker/docker-compose.yaml
docker/environment.yaml
setup.cfg
src/panoptes/utils/images/bayer.py
src/panoptes/utils/images/plot.py
tests/images/test_bayer.py

Misc edits during processing
* Default docker compose file to `develop` tag.
* Add `photutils` dependency in docker.
* Added an `RGB` IntEnum for easy iterating and consistent array access of rgb data.
* `get_stamp_slice` has `as_slices` param added with default `True` for legacy behavior. If `False` then just the four points are returned.
* `get_rgb_background` only accepts `data` as an argument.
* Updated defaults for `get_rgb_background`.
* Added `save_rgb_bg_fits` that will save a FITS files with seven extensions: combined rgb map, and then the background and rms maps for each color.
* `ruamel.yaml` added to base dependencies for use in serializes.

Processing usage updates

---

CHANGELOG.rst
src/panoptes/utils/images/fits.py

The `timeout` parameter from `get_solve_field` was being used only for the process timeout and wasn't being passed to `solve_field` for actual solving timeout. Default timeout (i.e. `cpulimit`) for `solve_field` was at 15 seconds.

Fix solve field timeout

---

CHANGELOG.rst
src/panoptes/utils/rs232.py

Small utility function to look up a serial device path by vendor and product id.  Can also return all `comport` devices that match if multiple devices with same vendor and product id are plugged in.

Lookup serial port from vendor and product id

---

docker/Dockerfile
docker/cloudbuild.yaml

Working directories for PANOPTES will follow the repo name for consistency, so everything from here will go into `/panoptes-utils`.
Also remove some build files from final image.

Docker cleanup - The Never Ending Story

---

CHANGELOG.rst
src/panoptes/utils/config/client.py
src/panoptes/utils/logging.py

Make the config getter and setter less noisy by default.
Remove old unused logging file.
Make `default` the second parameter for `get_config` to mimic `dict.get`.  Closes #268

Config client updates

---

.github/workflows/pythontest.yaml
CHANGELOG.rst
src/panoptes/utils/serial/device.py
tests/test_serial_device.py

* Removing unused params from `SerialDevice`.
* Remove the `BaseSerialReader` and move inline to the device to save a few lines of codecov. :)
* Testing Dockerfile has `privileged` permission to get device `loop`.

SerialDevice docs update

---

CHANGELOG.rst
docker/Dockerfile

Uses `condaforge//miniforge3` as the docker image base, which now supports `arm64`.
This should help reduce build times and image size.

Docker updates - condaforge base

---

CHANGELOG.rst
docker/Dockerfile
docker/environment.yaml
src/panoptes/utils/database/file.py

* Don't nest storage objects for the `PanFileDB`.
* Consistent multi-stage names in Dockerfile
* Add `jupyter_console` to image (we really need a `slim` version).

Fix PanFileDB Format and Docker updates

---

src/panoptes/utils/horizon.py
tests/test_horizon.py

- Fixes bug in `Horizon` caused by sorting obstruction points in azimuth
- `Obstruction` points lists must be in clockwise ordering
- Maintains backwards compatibility so it doesn't break `POCS`

revamp horizon class

---

src/panoptes/utils/config/cli.py
src/panoptes/utils/config/client.py
src/panoptes/utils/config/server.py

Allow config server to properly run on different port by fixing the `server_is_running` heartbeat check.
Also removes support for the `PANOPTES_CONFIG_FILE` env var.

Config server port fix.

---

CHANGELOG.rst
src/panoptes/utils/time.py
tests/test_time.py

Removing extra code related to a zero-second countdowntimer, which doesn't appear to be used anywhere. No real functionality is lost here other than the `is_non_blocking` predicate.

Remove non-blocking countdowntimer code.

---

.github/codecov.yml
setup.cfg
src/panoptes/utils/config/client.py
src/panoptes/utils/config/server.py

* Config server doesn't parse config as loaded so it doesn't need to serialize it before sending a response. The serialization should happen by the client side get_config.
* Restores the config server testing. Closes #296.
* Explicitly ignores the config server file for coverage even though it should be covered by the threads.

Fix config server testing
